#pragma once

const int WIDTH = 800;
const int HEIGHT = 400;

enum ID{PLAYER, ENEMY, BULLET, BORDER, MISC, EXPLOSION, POWERUP};
enum STATE{TITLE, PLAYING, LOST, HIGHSCORE, ENTERNAME, PAUSE};
enum TYPE{NORMAL, WIDE, BARRIER, LIFE, SHIELD};